apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    repository-permalinks:
      - "https://github.com/org4rong/py3ocp7ai-src/commit/28f7c937328c6f2ca840d626f0bae47e8cdc7a0b"
  name: py3ocp7ai-svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:28f7c937328c6f2ca840d626f0bae47e8cdc7a0b@sha256:cb16b8ac8211e4a2c7e7cd488ec0309fcb8eda171f787eb7884711a33f6a1cd2
          name: container-image
---
# RAG UI Ingestion Pipeline Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    repository-permalinks:
      - "https://github.com/org4rong/py3ocp7ai-src/commit/28f7c937328c6f2ca840d626f0bae47e8cdc7a0b"
  name: rag-ingestion-pipeline
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:28f7c937328c6f2ca840d626f0bae47e8cdc7a0b@sha256:cb16b8ac8211e4a2c7e7cd488ec0309fcb8eda171f787eb7884711a33f6a1cd2
          name: ingestion-pipeline
---
# RAG UI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    repository-permalinks:
      - "https://github.com/org4rong/py3ocp7ai-src/commit/28f7c937328c6f2ca840d626f0bae47e8cdc7a0b"
  name: rag
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:28f7c937328c6f2ca840d626f0bae47e8cdc7a0b@sha256:cb16b8ac8211e4a2c7e7cd488ec0309fcb8eda171f787eb7884711a33f6a1cd2
          name: rag
---
# LlamaStack Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    repository-permalinks:
      - "https://github.com/org4rong/py3ocp7ai-src/commit/28f7c937328c6f2ca840d626f0bae47e8cdc7a0b"
  name: llamastack
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:28f7c937328c6f2ca840d626f0bae47e8cdc7a0b@sha256:cb16b8ac8211e4a2c7e7cd488ec0309fcb8eda171f787eb7884711a33f6a1cd2
          name: llama-stack
---
# Toolhive Operator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
    repository-permalinks:
      - "https://github.com/org4rong/py3ocp7ai-src/commit/28f7c937328c6f2ca840d626f0bae47e8cdc7a0b"
  name: toolhive-operator
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:28f7c937328c6f2ca840d626f0bae47e8cdc7a0b@sha256:cb16b8ac8211e4a2c7e7cd488ec0309fcb8eda171f787eb7884711a33f6a1cd2
          name: manager
