apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: py3ocp7ai-svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:0dc6a78906973ac189c468bfe5fcc02e6d788d1a@sha256:082849a7ab76a5a509e592eeedc20acd2c2bb10a3363c18dd136926bd4a60824
          name: container-image
---
# RAG UI Ingestion Pipeline Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag-ingestion-pipeline
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:0dc6a78906973ac189c468bfe5fcc02e6d788d1a@sha256:082849a7ab76a5a509e592eeedc20acd2c2bb10a3363c18dd136926bd4a60824
          name: ingestion-pipeline
---
# RAG UI Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rag
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:0dc6a78906973ac189c468bfe5fcc02e6d788d1a@sha256:082849a7ab76a5a509e592eeedc20acd2c2bb10a3363c18dd136926bd4a60824
          name: rag
---
# LlamaStack Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: llamastack
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:0dc6a78906973ac189c468bfe5fcc02e6d788d1a@sha256:082849a7ab76a5a509e592eeedc20acd2c2bb10a3363c18dd136926bd4a60824
          name: llama-stack
---
# Toolhive Operator Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: toolhive-operator
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/org4rong/py3ocp7ai-img:0dc6a78906973ac189c468bfe5fcc02e6d788d1a@sha256:082849a7ab76a5a509e592eeedc20acd2c2bb10a3363c18dd136926bd4a60824
          name: manager
